### ISSUE TITLE
Where do you need such batch conversion?

### ISSUE THREAD

**Issue by 8fdafs2** [zhanglongtai/CATIA_IGES_to_Bodies_with_Python#1]
For a quick view I can see it's a script doing batch conversion job.
Not test it yet.
But from iges to catpart... just don't know where do you need such batch conversion?

**Comment by zhanglongtai** [comment]
@8fdafs2 Because I need to assemble all the iges-components in CATIA, it should do the conversion.

**Comment by 8fdafs2** [comment]
Correct me if I am wrong :)
The component you wanna insert into an assembly can be of type either catpart or **igs** or some other types that catia can accept, so why bother to batch convert your .igs files first?
The usage of this script should be very specific...

**Comment by zhanglongtai** [comment]
@8fdafs2 In my impression, I had encountered some problems when I used surfaces directly, so I tried to convert the surfaces into entities, sorry I don't remember the details.

**Comment by 8fdafs2** [comment]
Yes very often I forgot something about the code I wrote myself months ago.
This issue will be closed since it's never a real **issue** ;)
Thank you for your time.

**Comment by zhanglongtai** [comment]
@8fdafs2 You're welcome, it's a pleasure to have a communicate with a CAE engineer on GitHub.
